development:
  STRIPE_API_KEY: 
  STRIPE_PUBLIC_KEY: 
  STRIPE_CONNECT_CLIENT_ID: 
  STRIPE_APPLICATION_FEE: 1
  STRIPE_CURRENCY: 'cad'
  DEFAULT_EMAIL_SENDER: "app@domain.com"
  DEFAULT_ADMIN_EMAIL: "admin@domain.com"
  DEFAULT_CONTACT_EMAIL: "contact@domain.com"
  FACEBOOK_NIC:
  TWITTER_NIC:
  PINTEREST_NIC: 